services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:rpc
    container_name: server
    volumes:
      - ./server.py:/app/main.py
    ports:
      - 50051:50051

  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:rpc
    container_name: client
    volumes:
      - ./client.py:/app/main.py
    ports:
      - 8000:8000
    command: ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - server
